[package]
name = "hello_world"
version = "0.1.0"
authors = ["Sumer Malhotra <sumer@genesisblockhk.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
